[package]
name = "horsenuggets/luauproject-cli"
description = "A CLI tool for instantiating new Luau projects."
version = "0.1.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/horsenuggets/luauproject-cli"
realm = "shared"
private = true

[dependencies]
Chalk = "horsenuggets/chalk-luau@0.1.0"
Commandline = "horsenuggets/commandline-luau@0.0.5"

[dev-dependencies]
Testable = "horsenuggets/testable@0.1.0"
